# Generated by Django 4.0.4 on 2022-05-29 12:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('select', models.CharField(choices=[('CHG', 'Collaborate with Honoour Ghana'), ('CHW', 'Create a Culture of Honour at my Work Place'), ('JHC', 'Join an Honour Champions Community'), ('PSS', 'Be a Partner or Sponsor of short films'), ('PFH', 'Pitch a short film about Honour'), ('HSS', 'Honour someone special'), ('OTE', 'Other enquiry')], max_length=3)),
                ('your_message', models.TextField()),
            ],
        ),
    ]
