# Generated by Django 4.0.4 on 2022-06-01 11:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honour_main', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default='tim'),
            preserve_default=False,
        ),
    ]
