# Generated by Django 4.0.4 on 2022-06-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honour_main', '0005_news_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
