# Generated by Django 4.0.4 on 2022-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honour_main', '0009_alter_contact_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='select_category',
            field=models.CharField(choices=[('others', 'others'), ('newsletter', 'newsletter')], default='others', max_length=15),
        ),
    ]
